### ISSUE TITLE
minimum image size?

### ISSUE THREAD

**Issue by neilkale** [IDEA-Research/Grounded-SAM-2#70]
I am trying to run `grounded_sam2_local_demo.py` on the image below, but I am finding the following stack trace. Is there a minimum image size for SAM2, or is some other issue at play?

`Traceback (most recent call last):
  File "/home/nkale/ml_projects/Grounded-SAM-2/grounded_sam2_local_demo.py", line 80, in <module>
    masks, scores, logits = sam2_predictor.predict(
  File "/home/nkale/ml_projects/Grounded-SAM-2/sam2/sam2_image_predictor.py", line 291, in predict
    masks, iou_predictions, low_res_masks = self._predict(
  File "/home/nkale/miniconda3/envs/gsam2env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/nkale/ml_projects/Grounded-SAM-2/sam2/sam2_image_predictor.py", line 420, in _predict
    low_res_masks, iou_predictions, _, _ = self.model.sam_mask_decoder(
  File "/home/nkale/miniconda3/envs/gsam2env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/nkale/miniconda3/envs/gsam2env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/nkale/ml_projects/Grounded-SAM-2/sam2/modeling/sam/mask_decoder.py", line 136, in forward
    masks, iou_pred, mask_tokens_out, object_score_logits = self.predict_masks(
  File "/home/nkale/ml_projects/Grounded-SAM-2/sam2/modeling/sam/mask_decoder.py", line 203, in predict_masks
    assert image_embeddings.shape[0] == tokens.shape[0]
AssertionError`

![image](https://github.com/user-attachments/assets/cc784ac9-86e1-456f-b8e7-bdebd93996c8)

**Comment by ShuoShenDe** [comment]
Hi~Dear,

To help us debug the issue more effectively, could you please provide the following additional information:

Input details:
How are you loading and preprocessing the image before passing it to the model?

Environment details:
Could you share your system configuration, such as the version of Python, PyTorch, and any relevant libraries you're using?

Additional runtime information:
Please output and share the shapes of image_embeddings and tokens just before the assertion error occurs. This will help us understand the source of the mismatch.

Shuo Shen

**Comment by sunjian2015** [comment]
> I am trying to run `grounded_sam2_local_demo.py` on the image below, but I am finding the following stack trace. Is there a minimum image size for SAM2, or is some other issue at play?
> 
> `Traceback (most recent call last): File "/home/nkale/ml_projects/Grounded-SAM-2/grounded_sam2_local_demo.py", line 80, in <module> masks, scores, logits = sam2_predictor.predict( File "/home/nkale/ml_projects/Grounded-SAM-2/sam2/sam2_image_predictor.py", line 291, in predict masks, iou_predictions, low_res_masks = self._predict( File "/home/nkale/miniconda3/envs/gsam2env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context return func(*args, **kwargs) File "/home/nkale/ml_projects/Grounded-SAM-2/sam2/sam2_image_predictor.py", line 420, in _predict low_res_masks, iou_predictions, _, _ = self.model.sam_mask_decoder( File "/home/nkale/miniconda3/envs/gsam2env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/nkale/miniconda3/envs/gsam2env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl return forward_call(*args, **kwargs) File "/home/nkale/ml_projects/Grounded-SAM-2/sam2/modeling/sam/mask_decoder.py", line 136, in forward masks, iou_pred, mask_tokens_out, object_score_logits = self.predict_masks( File "/home/nkale/ml_projects/Grounded-SAM-2/sam2/modeling/sam/mask_decoder.py", line 203, in predict_masks assert image_embeddings.shape[0] == tokens.shape[0] AssertionError`
> 
> ![image](https://github.com/user-attachments/assets/cc784ac9-86e1-456f-b8e7-bdebd93996c8)

Have you solve it? I meet the same question...

**Comment by ShuoShenDe** [comment]
> > I am trying to run `grounded_sam2_local_demo.py` on the image below, but I am finding the following stack trace. Is there a minimum image size for SAM2, or is some other issue at play?
> > `Traceback (most recent call last): File "/home/nkale/ml_projects/Grounded-SAM-2/grounded_sam2_local_demo.py", line 80, in <module> masks, scores, logits = sam2_predictor.predict( File "/home/nkale/ml_projects/Grounded-SAM-2/sam2/sam2_image_predictor.py", line 291, in predict masks, iou_predictions, low_res_masks = self._predict( File "/home/nkale/miniconda3/envs/gsam2env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context return func(*args, **kwargs) File "/home/nkale/ml_projects/Grounded-SAM-2/sam2/sam2_image_predictor.py", line 420, in _predict low_res_masks, iou_predictions, _, _ = self.model.sam_mask_decoder( File "/home/nkale/miniconda3/envs/gsam2env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/nkale/miniconda3/envs/gsam2env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl return forward_call(*args, **kwargs) File "/home/nkale/ml_projects/Grounded-SAM-2/sam2/modeling/sam/mask_decoder.py", line 136, in forward masks, iou_pred, mask_tokens_out, object_score_logits = self.predict_masks( File "/home/nkale/ml_projects/Grounded-SAM-2/sam2/modeling/sam/mask_decoder.py", line 203, in predict_masks assert image_embeddings.shape[0] == tokens.shape[0] AssertionError`
> > ![image](https://github.com/user-attachments/assets/cc784ac9-86e1-456f-b8e7-bdebd93996c8)
> 
> Have you solve it? I meet the same question...

hi dear, I think the error occurs because the model detect zero target object from the image. So just pass this situation, we have solve it in the grounded_sam2_tracking_demo_with_continuous_id_gd1.5.py

**Comment by vignesht30** [comment]
Yes. i got this error while playing with 
https://github.com/IDEA-Research/Grounded-SAM-2/blob/main/grounded_sam2_hf_model_demo.py

Looks like if the hf model doesnt detect any bb in the onput image then sam2_image_predictor.py throws this error
