### ISSUE TITLE
KeyError: 'grounding-dino'

### ISSUE THREAD

**Issue by supersonicMaclaurin** [IDEA-Research/Grounded-SAM-2#72]

**Comment by supersonicMaclaurin** [comment]
Traceback (most recent call last):   File "/workspace/Exp/Grounded-SAM-2-main/grounded_sam2_tracking_demo.py", line 38, in <module>     grounding_model = AutoModelForZeroShotObjectDetection.from_pretrained(model_id).to(device)   File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/auto_factory.py", line 527, in from_pretrained     config, kwargs = AutoConfig.from_pretrained(   File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 1039, in from_pretrained     config_class = CONFIG_MAPPING[config_dict["model_type"]]   File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 734, in __getitem__     raise KeyError(key) KeyError: 'grounding-dino'

**Comment by supersonicMaclaurin** [comment]
solved.

**Comment by kynthesis** [comment]
solved by 
`pip install 'transformers>4.33.2'`

**Comment by yangxu-debug** [comment]
> solved.

how to solve it ?
